method_name: 'ensembled'
seed: 3698
models:
    XGBoost:
        name: 'XGBoost'
        result_ratio: 0.0
        args:
            n_estimators: 500 #200
            max_depth: 7 #7
            max_features: "auto"
            min_samples_split: 7
            min_samples_leaf: 3
            learning_rate: 0.01 #0.17
            gamma: 1
            reg_alpha: 0
            reg_lambda: 1
    LightGBM:
        name: 'LightGBM'
        result_ratio: 1.0
        args:
            n_estimators: 500
            metric: "rmse"
            num_leaves: 100
            learning_rate: 0.001
            bagging_fraction: 0.6
            feature_fraction: 0.6
            bagging_frequency: 6
            bagging_seed: 42
            verbosity: -1
            seed: 42

dataset:
    train:
        name: data-train
        args:
            path: 'data/train/processed/input'
            split_ratio: 0.22
        
    test:
        name: public-test
        args:
            path: 'data/public-test/processed/input'
            n_neighbor: 4